awslabs/nx-plugin-for-aws

packages/nx-plugin/src/open-api/ts-client/__snapshots__/generator.spec.ts.snap
packages/nx-plugin/src/open-api/ts-client/files/client.gen.ts.template
packages/nx-plugin/src/open-api/ts-client/files/types.gen.ts.template
packages/nx-plugin/src/open-api/ts-client/generator.spec.ts

FastAPI generates an OpenAPI specification which uses the OpenAPI v3.1 "null" type when a property is typed as `Optional[xxx]`. Specifically it creates a composite `anyOf` schema for the actual type and `null`, eg:
`Optional[str]` becomes `"anyOf": [{ type: "string" }, { type: "null" }]`
The templates had a bug where we'd test `typeof property === 'null'` to discriminate between such composite types, which is invalid TypeScript.
Fix the bug by ensuring we don't test `typeof property === 'null'` - we already test `property === null` above so we don't need to replace it with anything.
Additionally ensure we don't generate `null | null` as the type for properties which are just null (we were adding `| null` to the type if a field is nullable, but the type is already `null` so we ended up …

fix(api-connection): fix generated client compilation issues for optional fields

---

packages/nx-plugin/src/py/project/generator.spec.ts
packages/nx-plugin/src/py/project/generator.ts

`/reports` and `__pycache__` are created from building/testing a python project and should not be committed to version control
Add appropriate patterns to `.gitignore`
Unit tests, and updated .gitignores with same patterns in example dungeon adventure repo
Fixes #93
----

fix(py#project): ignore reports and pycache files in version control

---

docs/src/content/docs/get_started/tutorials/dungeon-game/3.mdx
packages/nx-plugin/src/trpc/backend/__snapshots__/generator.spec.ts.snap
packages/nx-plugin/src/utils/files/http-api/common/constructs/src/core/http-api.ts.template

More intuitive/flexible granting of permissions to call http apis
Instead of requiring a `Role`, we loosen the constraint to an `IGrantable` which allows for more flexible permission granting, for example a lambda can be passed to `grantInvokeAccess` rather than that lambda's role:
```ts
// before
api.grantInvokeAccess(someFunction.role!);
// after
api.grantInvokeAccess(someFunction);
```
* Unit tests
* Deployed a sample project
Fixes #95
----

feat(http-api): use grantable instead of role for granting invoke access to apis

---

packages/nx-plugin/src/open-api/ts-client/__snapshots__/generator.additional-properties.spec.ts.snap
packages/nx-plugin/src/open-api/ts-client/files/client.gen.ts.template
packages/nx-plugin/src/open-api/ts-client/files/types.gen.ts.template
packages/nx-plugin/src/open-api/ts-client/generator.additional-properties.spec.ts
packages/nx-plugin/src/open-api/utils/codegen-data.ts
packages/nx-plugin/src/open-api/utils/normalise.ts

Schemas which mixed objects and additional properties were causing clients to be generated which did not compile.
We'd render invalid code like `$IO.unknown.toJson(xxxx)`.
Additionally, `patternProperties` are part of the JSON schema version used by OpenAPI v3.1, and so therefore should be handled too.
This change adds support for additional properties and pattern properties.
Models for schemas with both explicit properties and additional properties were represented in multiple different ways, which were being treated differently in code generation (some had `export: "dictionary"`, others had `export: "interface"` but with a property named `[key: string]`).
As part of constructing the data structure for codegen, we now standardise on the following:
- `export: "dictionary"` means a proper …

fix(open-api): handle object schemas with additional properties and pattern properties

---

docs/src/content/docs/get_started/tutorials/dungeon-game/1.mdx
docs/src/content/docs/get_started/tutorials/dungeon-game/3.mdx
docs/src/content/docs/get_started/tutorials/dungeon-game/4.mdx
docs/src/content/docs/guides/api-connection/react-fastapi.mdx
docs/src/content/docs/guides/fastapi.mdx
package.json
packages/nx-plugin/.eslintrc.json
packages/nx-plugin/src/open-api/ts-client/files/client.gen.ts.template
packages/nx-plugin/src/open-api/ts-client/generator.utils.spec.ts
packages/nx-plugin/src/open-api/ts-hooks/__snapshots__/generator.spec.tsx.snap
packages/nx-plugin/src/open-api/ts-hooks/files/options-proxy.gen.ts.template
packages/nx-plugin/src/open-api/ts-hooks/generator.spec.tsx
packages/nx-plugin/src/open-api/ts-hooks/generator.ts
packages/nx-plugin/src/open-api/utils/codegen-data.ts
packages/nx-plugin/src/open-api/utils/codegen-data/types.ts
packages/nx-plugin/src/py/fast-api/react/__snapshots__/generator.spec.ts.snap
packages/nx-plugin/src/py/fast-api/react/files/website/components/__apiNameClassName__Provider.tsx.template
packages/nx-plugin/src/py/fast-api/react/files/website/hooks/use__apiNameClassName__.tsx.template
packages/nx-plugin/src/py/fast-api/react/files/website/hooks/use__apiNameClassName__Client.tsx.template
packages/nx-plugin/src/py/fast-api/react/generator.spec.ts
packages/nx-plugin/src/py/fast-api/react/generator.ts
packages/nx-plugin/tsconfig.lib.json
packages/nx-plugin/tsconfig.spec.json
pnpm-lock.yaml

* No need for users to manage state manually
* More consistent with tRPC
This change implements the open-api#ts-hooks generator, which provides factory methods for options to provide to tanstack query hooks, in a similar manner to tRPC.
This saves the need for users to manage state themselves, and provides parity with tRPC.
By default, PUT/PATCH/POST/DELETE http requests are considered "mutations" and all others "queries". This behaviour can be overridden with `x-mutation` and `x-query` vendor extensions however.
Similarly to tRPC, if an operation accepts a `cursor` parameter, we consider this a paginated operation and generate an `infiniteQueryOptions` method alongside the `queryOptions` method. If an operation is paginated but has a different pagination parameter name, this can be …

feat(api-connection): tanstack query hooks for connecting react to fastapi

---

docs/src/content/docs/guides/api-connection/react-fastapi.mdx
packages/nx-plugin/LICENSE-THIRD-PARTY
packages/nx-plugin/src/py/fast-api/__snapshots__/generator.spec.ts.snap
packages/nx-plugin/src/py/fast-api/files/app/__name__/init.py.template
packages/nx-plugin/src/py/fast-api/files/app/__name__/main.py.template

For tRPC we generate an echo procedure as an example to follow. For FastAPI we were generating a read_root operation which can be confusing for users.
We update to generate an echo route for consistency with tRPC. Additionally, we define a model for the response returned by the unhandled exception middleware for better error handling in the generated code when using the api-connection.
Deployed and verified the echo operation works!
Fixes #92
----

feat(fastapi): generate an echo api by default for consistency with trpc

---

docs/src/content/docs/get_started/tutorials/dungeon-game/1.mdx
docs/src/content/docs/get_started/tutorials/dungeon-game/2.mdx
docs/src/content/docs/get_started/tutorials/dungeon-game/3.mdx
docs/src/content/docs/get_started/tutorials/dungeon-game/4.mdx
docs/src/content/docs/get_started/tutorials/dungeon-game/wrap-up.mdx
docs/src/content/docs/guides/cloudscape-website.mdx
packages/nx-plugin/src/cloudscape-website/app/generator.ts
packages/nx-plugin/src/infra/app/__snapshots__/generator.spec.ts.snap
packages/nx-plugin/src/infra/app/files/app/src/main.ts.template
packages/nx-plugin/src/infra/app/generator.ts

In order to better identify AWS resources, we prefix the stack id with the project namespace.
* Prefix stack id with npm scope (this will be `monorepo` if there's no root package.json scope).
* Updated load:runtime-config task to use the updated stack id
* Updated the dungeon adventure tutorial to reflect the new stack id
Tested in a local project
Fixes #85
----

fix(infra): include namespace in application stack id

---

.github/workflows/ci.yml

Releases to NPM have been failing since 0.17.0!
```
pnpm publish error:
422 Unprocessable Entity - PUT https://registry.npmjs.org/@aws%2fnx-plugin - Error verifying sigstore provenance bundle: Unsupported GitHub Actions runner environment: "self-hosted". Only "github-hosted" runners are supported when publishing with provenance.
```
Disabled provenance
----

ci(release): fix release since provenance is not supported on self-hosted runners

---

packages/nx-plugin/src/cloudscape-website/app/__snapshots__/generator.spec.ts.snap
packages/nx-plugin/src/cloudscape-website/app/files/common/constructs/src/core/static-website.ts.template

Error when deploying reasonable-sized bundles
Increase memory limit for bucket deployment
Sample project
Fixes #139
----

fix(ts#cloudscape-website): increase memory limit for website deployment

---

package.json
packages/nx-plugin/src/open-api/ts-hooks/__snapshots__/generator.spec.tsx.snap
packages/nx-plugin/src/open-api/ts-hooks/files/options-proxy.gen.ts.template
packages/nx-plugin/src/utils/versions.ts
pnpm-lock.yaml

TanStack Query v5.74.3 removed the data and error type parameters from the QueryFilters type.
See: https://github.com/TanStack/query/pull/8958
Remove these type parameters in the generated code
Updated TanStack query in an example project
Fixes #147
----

fix(api-connection): fix options proxy query filter type error with tanstack query v5.74.3

---

packages/nx-plugin/src/utils/__snapshots__/shared-constructs.spec.ts.snap
packages/nx-plugin/src/utils/files/common/constructs/src/core/app.ts.template

Tags weren't showing up in our metrics
The correct key is 'tag' not 'tags', updated template to fix.
----

chore(metrics): fix tag key in cloudformation description

---

packages/nx-plugin/src/cloudscape-website/app/generator.ts

`preview` and `serve-static` targets both rely on the outputPath of the build task to determine where the static files are located. The two options are to either:
1.) update the `outputPath` to point to the bundle (this PR)
2.) add a `staticFilePath` to each of `preview` and `serve-static` to point to the bundle.
I have chosen to implement 1 as the `outputPath` of the `build` target is not used presently and the primary output is the `bundle`.
- updated outputPath of `build` to be the generated bundle.
- local testing.
----

fix(cloudscape-website): update build outputPath to the bundle

---

packages/nx-plugin/src/cloudscape-website/app/__snapshots__/generator.spec.ts.snap
packages/nx-plugin/src/cloudscape-website/app/files/common/constructs/src/core/static-website.ts.template
packages/nx-plugin/src/cloudscape-website/app/generator.ts

`website:load:runtime-config` currently pulls `runtime-config.json` via web request. If there are changes during the deployment, it won't be reflected for quite some time, invalidations during deployment are not predictable (at least based on my experience).
Since AWS CLI is used in the current version, a direct s3 download is a viable option and the latest deployment's changes are reflected immediately.
Unit tests
Closes #<issue number here>.
----

feat(cloudscape-website): load runtimeconfig from s3 bucket

---

packages/nx-plugin/src/setup-tests.ts
packages/nx-plugin/vite.config.mts

Unit tests have been flakey recently - seems to be due to the project graph being calculated for every test and the daemon deadlocking and timing out.
Create the project graph before running any tests to ensure it's cached in the daemon before spamming it with graph requests.
A couple of PR builds lol
----

test: create project graph prior to running tests

---

.github/workflows/ci.yml
.github/workflows/pr.yml
e2e/src/smoke-tests/dungeon-adventure.spec.ts
e2e/src/smoke-tests/smoke-test.ts
e2e/src/utils.ts
package.json
packages/nx-plugin/package.json
packages/nx-plugin/src/utils/versions.ts
packages/nx-plugin/vite.config.mts
pnpm-lock.yaml

- The `env` in vite config wasn't actually enabling the daemon in the unit tests. With the daemon on in the unit tests it's the same behaviour as running them locally and seems to be passing a bit more consistently! I've updated the gitlab workflows to ensure it's set, but have disabled it in the e2e tests as daemon errors started to pop up.
- Reduce parallelism to 1 in smoke tests to avoid transient python clashing issue
- Upgrade @nxlv/python to 21 in line with Nx 21
----

test: enable daemon in unit tests

---

packages/nx-plugin/src/py/project/generator.spec.ts
packages/nx-plugin/src/py/project/generator.ts

Add .coverage to .gitignore as it's generated at build time
----

fix(py#project): ignore .coverage build artifact

---

README.md
package.json
packages/nx-plugin/LICENSE-THIRD-PARTY
packages/nx-plugin/README.md
packages/nx-plugin/bin/aws-nx-mcp.ts
packages/nx-plugin/generators.json
packages/nx-plugin/package.json
packages/nx-plugin/project.json
packages/nx-plugin/src/mcp-server/generator-info.spec.ts
packages/nx-plugin/src/mcp-server/generator-info.ts
packages/nx-plugin/src/mcp-server/index.ts
packages/nx-plugin/src/mcp-server/schema.ts
packages/nx-plugin/src/mcp-server/server.spec.ts
packages/nx-plugin/src/mcp-server/server.ts
packages/nx-plugin/src/mcp-server/tools/create-workspace-command.ts
packages/nx-plugin/src/mcp-server/tools/general-guidance.ts
packages/nx-plugin/src/mcp-server/tools/generator-guide.ts
packages/nx-plugin/src/mcp-server/tools/list-generators.ts
packages/nx-plugin/src/utils/nx.ts
packages/nx-plugin/src/utils/versions.ts
packages/nx-plugin/tsconfig.lib.json
pnpm-lock.yaml

A first attempt at an MCP server for the Nx Plugin for AWS. This is all subject to change and I am yet to write docs as there are some additional changes to the Nx plugin that would help AI to use it, which I would like to make separately.
This gets the base functionality out and gives us something to iterate on.
Add an MCP server with several tools which provide information to AI assistants regarding how to use the Nx Plugin for AWS.
- `general-guidance` for guidance and best practices for working with Nx and the Nx Plugin for AWS.
- `create-workspace-command` to discover how to create a workspace to start a new project.
- `list-generators` to discover the available generators and how to run them.
- `generator-guide` to retrieve detailed information about a specific generator.
Tested out …

feat(aws-nx-mcp): Add an MCP server to uplift usage with AI assistants

---

e2e/src/smoke-tests/smoke-test.ts
packages/nx-plugin/src/api-connection/generator.spec.ts
packages/nx-plugin/src/api-connection/generator.ts
packages/nx-plugin/src/cloudscape-website/cognito-auth/generator.spec.ts
packages/nx-plugin/src/cloudscape-website/cognito-auth/generator.ts
packages/nx-plugin/src/cloudscape-website/runtime-config/generator.ts
packages/nx-plugin/src/mcp-server/tools/general-guidance.ts
packages/nx-plugin/src/py/fast-api/react/generator.spec.ts
packages/nx-plugin/src/py/fast-api/react/generator.ts
packages/nx-plugin/src/py/lambda-function/generator.spec.ts
packages/nx-plugin/src/py/lambda-function/generator.ts
packages/nx-plugin/src/trpc/react/generator.spec.ts
packages/nx-plugin/src/trpc/react/generator.ts
packages/nx-plugin/src/ts/nx-generator/generator.ts
packages/nx-plugin/src/utils/nx.spec.ts
packages/nx-plugin/src/utils/nx.ts
packages/nx-plugin/src/utils/paths.ts

Saves some typing when running generators. Additionally in my MCP server testing I've found that despite the guidance saying to use the fully qualified name, models will often still specify the unqualified name.
Instead of always needing to specify the fully-qualified project name, we let users specify a short project name.
Unit tests and smoke tests
----

feat: allow specifying short project names in generator arguments

---

eslint/index.js
eslint/package.json
eslint/rules/require-mcp-js-extension.js
package.json
packages/nx-plugin/.eslintrc.json
pnpm-lock.yaml

Despite the `@aws/nx-plugin` package being `commonjs`, imports for the mcp sdk must use the esm-style `.js` extensions in order for the dependencies to be resolved correctly at runtime. TypeScript compilation doesn't complain if using the syntax without the extension, and neither does vitest.
Add a custom eslint rule to defend against accidentally omitting the extension.
Intentionally omitted a `.js` extension and observed lint rule pick it up, and add it with `--fix` option.
----

chore(mcp-server): add a custom lint rule to ensure mcp sdk is correctly imported

---

packages/nx-plugin/src/py/lambda-function/generator.spec.ts
packages/nx-plugin/src/py/lambda-function/generator.ts

The dependency wasn't specifying the project, but instead the function name which isn't a target/project to depend on.
Fix to ensure the python lambda project's build target is depended on by common constructs.
----

fix(py#lambda-function): fix dependency added to common/constructs

---

packages/nx-plugin/src/mcp-server/server.spec.ts
packages/nx-plugin/src/mcp-server/server.ts
packages/nx-plugin/src/mcp-server/tools/create-workspace-command.ts
packages/nx-plugin/src/mcp-server/tools/general-guidance.ts
packages/nx-plugin/src/mcp-server/tools/generator-guide.ts
packages/nx-plugin/src/mcp-server/tools/list-generators.ts

Amazon Q CLI doesn't load tools unless they have a description!
https://github.com/aws/amazon-q-developer-cli/blob/972adf4c445b0486dfb991b10bfeabc6cb4cc498/crates/chat-cli/src/cli/chat/tool_manager.rs#L1245-L1248
Add a description to every tool, and enforce it with a test.
Also use the package version for the server version.
Pointed Q at local server and observed tools!
----

fix(mcp-server): ensure each tool has a description

---

packages/nx-plugin/src/open-api/ts-client/__snapshots__/generator.arrays.spec.ts.snap
packages/nx-plugin/src/open-api/ts-client/__snapshots__/generator.complex-types.spec.ts.snap
packages/nx-plugin/src/open-api/ts-client/__snapshots__/generator.composite-types.spec.ts.snap
packages/nx-plugin/src/open-api/ts-client/files/client.gen.ts.template
packages/nx-plugin/src/open-api/ts-client/generator.arrays.spec.ts
packages/nx-plugin/src/open-api/ts-client/generator.petstore.spec.ts
packages/nx-plugin/src/open-api/ts-hooks/files/options-proxy.gen.ts.template
packages/nx-plugin/src/open-api/ts-hooks/generator.spec.tsx

There were two issues with array requests/responses. Firstly when the request body is an array, we'd get a type error in the client `typeof someArray === 'object'` was always true. Secondly when the response is an array of objects the options proxy would incorrectly import `Array<ObjectType>` which is invalid syntax.
Fix both issues in the templates
Unit tests. Added petstore unit test to both client and hooks which is the default OpenAPI example spec that has lots of mixtures of types.
Fixes #201
----

fix(open-api): fix code generation issues with array requests and responses

---

packages/nx-plugin/src/cloudscape-website/app/__snapshots__/generator.spec.ts.snap
packages/nx-plugin/src/cloudscape-website/app/files/app/src/main.tsx.template
packages/nx-plugin/src/cloudscape-website/app/files/app/src/routes/__root.tsx.template

With the introduction of Verified Permissions, a method is needed to pass context into the router. This allows for authentication, runtimeConfig and other data to be used in routing decisions (such as authentication and authorization).
Introduction of a RouterProviderContextType that includes and auth and runtime object. These are provided to the RouterProvider in the RouterProvider of main.tsx. This also introduces createRootRouteWithContext into __root.tsx.
All builds and tests (including snapshots) tested locally.
----

refactor(website): Introduce router context

---

docs/src/content/docs/en/get_started/tutorials/dungeon-game/3.mdx
docs/src/content/docs/en/guides/python-project.mdx
docs/src/content/docs/es/get_started/tutorials/dungeon-game/3.mdx
docs/src/content/docs/es/guides/python-project.mdx
docs/src/content/docs/fr/get_started/tutorials/dungeon-game/3.mdx
docs/src/content/docs/fr/guides/python-project.mdx
docs/src/content/docs/it/get_started/tutorials/dungeon-game/3.mdx
docs/src/content/docs/it/guides/python-project.mdx
docs/src/content/docs/jp/get_started/tutorials/dungeon-game/3.mdx
docs/src/content/docs/jp/guides/python-project.mdx
docs/src/content/docs/ko/get_started/tutorials/dungeon-game/3.mdx
docs/src/content/docs/ko/guides/python-project.mdx
docs/src/content/docs/pt/get_started/tutorials/dungeon-game/3.mdx
docs/src/content/docs/pt/guides/python-project.mdx
docs/src/content/docs/zh/get_started/tutorials/dungeon-game/3.mdx
docs/src/content/docs/zh/guides/python-project.mdx
packages/nx-plugin/src/py/fast-api/generator.spec.ts
packages/nx-plugin/src/py/fast-api/generator.ts
packages/nx-plugin/src/py/lambda-function/generator.spec.ts
packages/nx-plugin/src/py/lambda-function/generator.ts
packages/nx-plugin/src/utils/bundle.ts

The bundle target for FastAPI and Python lambda functions was including the dependencies for all packages in the workspace, rather than just those for the target package. 
Updated to include only the appropriate dependencies.
Also fix the python documentation on local dependencies as it was incorrect.
Created and bundled multiple packages in a test project
----

fix(py): ensure bundle target only bundles required dependencies

---

CONTRIBUTING.md
README.md
packages/nx-plugin/README.md

README was outdated
- Linked to docs to remove duplication
- Also moved auto-translation to CONTRIBUTING.md as it's related to working in our library rather than using it.
----

docs: fix outdated quick start guide in readme

---

packages/nx-plugin/src/cloudscape-website/cognito-auth/generator.spec.ts
packages/nx-plugin/src/utils/ast.spec.ts
packages/nx-plugin/src/utils/ast.ts

Comments were previously being duplicated when performing AST operations. 
Ensure comments are preserved but not duplicated.
Also update ast tests to use a real tree instead of mocking the tree to be consistent with other tests.
Unit tests
Fixes #230
----

fix: do not duplicate comments in ast transforms

---

packages/nx-plugin/src/open-api/ts-client/__snapshots__/generator.arrays.spec.ts.snap
packages/nx-plugin/src/open-api/ts-client/__snapshots__/generator.composite-types.spec.ts.snap
packages/nx-plugin/src/open-api/ts-client/__snapshots__/generator.primitive-types.spec.ts.snap
packages/nx-plugin/src/open-api/ts-client/__snapshots__/generator.streaming.spec.ts.snap
packages/nx-plugin/src/open-api/ts-client/files/client.gen.ts.template
packages/nx-plugin/src/open-api/ts-client/generator.composite-types.spec.ts
packages/nx-plugin/src/open-api/ts-client/generator.primitive-types.spec.ts
packages/nx-plugin/src/utils/test/ts.spec.ts

Fix a few compilation issues for some OpenAPI edge cases
- Enums composed with other types would cause a compilation issue with the client trying to coerce a string to an enum
- When any (`{}`) was combined with null in a composite type, the client would fail to compile due to an invalid typeof check for 'unknown'
- The generated client would import all enum models, however only enum models that are top level request/response parameters are directly referenced by the client
Unit tests
----

fix(openapi): fixes for enums and composite types

---

package.json
packages/nx-plugin/package.json
packages/nx-plugin/src/py/project/generator.ts
packages/nx-plugin/src/utils/versions.ts
pnpm-lock.yaml

`@nxlv/python` published a new version of the uv project generator which requires `srcDir` and `buildSystem`.
This change adds those properties, setting them to the equivalent values of omitting them in the previous version for now.
We also pin the minor version of `@nxlv/python` to reduce the chance of similar issues in the future.
Created a python project, FastAPI and python lambda function.
Fixes #265
----

fix(py#project): missing srcdir error due to new version of nxlv python

---

packages/nx-plugin/src/ts/react-website/cognito-auth/generator.spec.ts
packages/nx-plugin/src/ts/react-website/cognito-auth/generator.ts

#258
Throw an error when a cognito domain is not specified
Unit tests
Fixes #258 
----

fix(ts#react-website#auth): validate missing cognito domain

---

packages/nx-plugin/src/py/fast-api/__snapshots__/generator.spec.ts.snap
packages/nx-plugin/src/py/fast-api/generator.spec.ts
packages/nx-plugin/src/py/fast-api/generator.ts
packages/nx-plugin/src/utils/api-constructs/api-constructs.ts
packages/nx-plugin/src/utils/api-constructs/files/app/apis/http/__apiNameKebabCase__.ts.template
packages/nx-plugin/src/utils/api-constructs/files/app/apis/rest/__apiNameKebabCase__.ts.template

I missed updating the lambda function handlers to use the normalised scope in https://github.com/awslabs/nx-plugin-for-aws/pull/229 - this means that FastAPI calls got a `Runtime.ImportModuleError` when being invoked unless a custom module name was provided.
Use the module name instead of the API name in the lambda function constructs.
Deployed a FastAPI
----

fix(py#fast-api): add missing scope to handler functions

---

.github/actions/init-monorepo/action.yml
docs/src/content/docs/en/get_started/tutorials/dungeon-game/3.mdx
docs/src/content/docs/en/guides/python-project.mdx
docs/src/content/docs/es/get_started/tutorials/dungeon-game/3.mdx
docs/src/content/docs/es/guides/python-project.mdx
docs/src/content/docs/fr/get_started/tutorials/dungeon-game/3.mdx
docs/src/content/docs/fr/guides/python-project.mdx
docs/src/content/docs/it/get_started/tutorials/dungeon-game/3.mdx
docs/src/content/docs/it/guides/python-project.mdx
docs/src/content/docs/jp/get_started/tutorials/dungeon-game/3.mdx
docs/src/content/docs/jp/guides/python-project.mdx
docs/src/content/docs/ko/get_started/tutorials/dungeon-game/3.mdx
docs/src/content/docs/ko/guides/python-project.mdx
docs/src/content/docs/pt/get_started/tutorials/dungeon-game/3.mdx
docs/src/content/docs/pt/guides/python-project.mdx
docs/src/content/docs/zh/get_started/tutorials/dungeon-game/3.mdx
docs/src/content/docs/zh/guides/python-project.mdx
packages/nx-plugin/src/py/project/generator.ts
packages/nx-plugin/src/ts/mcp-server/__snapshots__/generator.spec.ts.snap
packages/nx-plugin/src/ts/mcp-server/generator.spec.ts
packages/nx-plugin/src/ts/mcp-server/generator.ts
packages/nx-plugin/src/utils/agent-core-constructs/files/app/mcp-servers/__mcpServerNameKebabCase__/__mcpServerNameKebabCase__.ts.template
packages/nx-plugin/src/utils/bundle.ts

- `ts#mcp-server` - container is just using host platform, so won't work on an x86 machine
- `py#project` - doesn't install `@nxlv/python` meaning builds fail (unless you run another generator which does install deps prior to building)
- `py#lambda-function` and `py#fast-api` - bundle task was installing local workspace dependencies as editable, which doesn't work when deployed.
- Ensure platform is always arm64 for MCP servers as per https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/runtime-service-contract.html
- Install node dependencies for `py#project`
- Add `--no-deps` flag to `uv pip install` in bundle target - see https://github.com/astral-sh/uv/issues/13087
Ran and deployed
----
*By submitting this pull request, I confirm that my contribution is made under the terms …

fix: a few fixes in preparation for python mcp server

---

package.json
packages/nx-plugin/package.json
packages/nx-plugin/src/py/fast-api/generator.spec.ts
packages/nx-plugin/src/py/fast-api/generator.ts
packages/nx-plugin/src/py/lambda-function/generator.spec.ts
packages/nx-plugin/src/py/lambda-function/generator.ts
packages/nx-plugin/src/py/mcp-server/__snapshots__/generator.spec.ts.snap
packages/nx-plugin/src/py/mcp-server/generator.spec.ts
packages/nx-plugin/src/ts/react-website/app/generator.ts
packages/nx-plugin/src/utils/py.spec.ts
packages/nx-plugin/src/utils/py.ts
packages/nx-plugin/src/utils/versions.spec.ts
packages/nx-plugin/src/utils/versions.ts
pnpm-lock.yaml

To reduce the chance of breaking changes outside of our control, we add dependencies with specific version ranges in python generators.
- specify version ranges for all python dependencies our generators use
- use `addDependenciesToPyProjectToml` method everywhere we add dependencies, and add type safety
- parse existing dependencies to ensure we don't add duplicate entries with different versions for the same dependency
Unit/integ tests!
Fixes #269
----

fix(py): add python dependencies with version ranges in generators

---

docs/src/content/docs/en/get_started/tutorials/dungeon-game/1.mdx
docs/src/content/docs/es/get_started/tutorials/dungeon-game/1.mdx
docs/src/content/docs/fr/get_started/tutorials/dungeon-game/1.mdx
docs/src/content/docs/it/get_started/tutorials/dungeon-game/1.mdx
docs/src/content/docs/jp/get_started/tutorials/dungeon-game/1.mdx
docs/src/content/docs/ko/get_started/tutorials/dungeon-game/1.mdx
docs/src/content/docs/pt/get_started/tutorials/dungeon-game/1.mdx
docs/src/content/docs/zh/get_started/tutorials/dungeon-game/1.mdx
packages/nx-plugin/src/ts/react-website/app/__snapshots__/generator.spec.ts.snap
packages/nx-plugin/src/ts/react-website/cognito-auth/generator.spec.ts
packages/nx-plugin/src/ts/react-website/cognito-auth/generator.ts
packages/nx-plugin/src/ts/react-website/runtime-config/__snapshots__/generator.spec.ts.snap
packages/nx-plugin/src/ts/react-website/runtime-config/files/app/components/RuntimeConfig/index.tsx.template
packages/nx-plugin/src/ts/react-website/runtime-config/files/app/hooks/useRuntimeConfig.tsx.template
packages/nx-plugin/src/utils/__snapshots__/shared-constructs.spec.ts.snap
packages/nx-plugin/src/utils/api-constructs/api-constructs.ts
packages/nx-plugin/src/utils/files/common/constructs/src/core/runtime-config.ts.template
packages/nx-plugin/src/utils/files/common/types/src/index.ts.template
packages/nx-plugin/src/utils/files/common/types/src/runtime-config.ts.template
packages/nx-plugin/src/utils/shared-constructs-constants.ts
packages/nx-plugin/src/utils/shared-constructs.spec.ts
packages/nx-plugin/src/utils/shared-constructs.ts

An entire project dedicated to type safety for a few properties was overkill and added too much complexity to the generators which needed to perform ast transforms.
Removing this makes it easier to extend in future for eg Python backends consuming runtime configs or Terraform infrastructure writing them.
This change removes the common-types package and the IRuntimeConfig type, and instead the website just uses `any` for the result of reading `runtime-config.json`.
Created a test project with trpc, fastapi, website, infra. Built & deployed.
----

feat(runtime-config): remove common types package and types for runtime config

---

packages/nx-plugin/src/ts/lib/generator.spec.ts
packages/nx-plugin/src/ts/lib/generator.ts

The interactive cli (ie running with `pnpm nx g @aws/nx-plugin:ts#project` and answering the prompts) passes '' instead of undefined for subDirectory which caused the project to be created directly in packages unless the user expicitly specifies a subdirectory.
Addressed this by treating '' the same as undefined.
Added a unit test
----

fix(ts#project): creation of project in packages directory using nx interactive cli

---

.github/workflows/update-versions.yml

`pnpm i` fails on CI because the lockfile would change
`pnpm i --lockfile-only` to update the lockfile, then `pnpm i` to install
`CI=true pnpm i --lockfile-only && pnpm i` works locally :)
----

fix: update versions workflow
